"""add password_hash to cabinets

Revision ID: 2958b333bb8d
Revises: c81cb7cb6b23
Create Date: 2026-06-11 18:36:27.001200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2958b333bb8d'
down_revision: Union[str, None] = 'c81cb7cb6b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinets', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cabinets', 'password_hash')
    # ### end Alembic commands ###
