"""add is_admin to cabinets

Revision ID: 42a6e82f9be4
Revises: 2958b333bb8d
Create Date: 2026-06-11 19:19:40.380609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a6e82f9be4'
down_revision: Union[str, None] = '2958b333bb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default obligatoire : la table contient déjà des lignes
    op.add_column('cabinets', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cabinets', 'is_admin')
    # ### end Alembic commands ###
