"""initial schema

Revision ID: 7fe58d9a2eb6
Revises: 
Create Date: 2026-06-11 15:30:03.208584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe58d9a2eb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_active', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinets_email'), 'cabinets', ['email'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('file_mime_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('ocr_error', sa.Text(), nullable=True),
    sa.Column('ocr_raw_response', sa.JSON(), nullable=True),
    sa.Column('vendor_name', sa.String(length=512), nullable=True),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_ht', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_tva', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_ttc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tva_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pcg_account', sa.String(length=16), nullable=True),
    sa.Column('pcg_label', sa.String(length=255), nullable=True),
    sa.Column('pcg_source', sa.String(length=32), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_cabinet_id'), 'invoices', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit_price_ht', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_ht', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tva_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pcg_account', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_invoice_id'), 'line_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_items_invoice_id'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_cabinet_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_cabinets_email'), table_name='cabinets')
    op.drop_table('cabinets')
    # ### end Alembic commands ###
