"""add pcg_custom_rules table

Revision ID: 8d50cebf9305
Revises: 42a6e82f9be4
Create Date: 2026-06-11 19:36:46.635023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d50cebf9305'
down_revision: Union[str, None] = '42a6e82f9be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcg_custom_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cabinet_id', sa.UUID(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcg_custom_rules_cabinet_id'), 'pcg_custom_rules', ['cabinet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pcg_custom_rules_cabinet_id'), table_name='pcg_custom_rules')
    op.drop_table('pcg_custom_rules')
    # ### end Alembic commands ###
