"""add file_hash to invoices

Revision ID: c81cb7cb6b23
Revises: 7fe58d9a2eb6
Create Date: 2026-06-11 16:28:55.854494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81cb7cb6b23'
down_revision: Union[str, None] = '7fe58d9a2eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_invoices_file_hash'), 'invoices', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_file_hash'), table_name='invoices')
    op.drop_column('invoices', 'file_hash')
    # ### end Alembic commands ###
