"""add disabled_pcg_rules to cabinets

Revision ID: ec4145de9606
Revises: 8d50cebf9305
Create Date: 2026-06-11 20:48:21.785256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4145de9606'
down_revision: Union[str, None] = '8d50cebf9305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default obligatoire : la table contient déjà des lignes
    op.add_column('cabinets', sa.Column('disabled_pcg_rules', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cabinets', 'disabled_pcg_rules')
    # ### end Alembic commands ###
