"""add plan to cabinets

Revision ID: f258e396dfff
Revises: ec4145de9606
Create Date: 2026-06-11 23:49:29.570911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f258e396dfff'
down_revision: Union[str, None] = 'ec4145de9606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default obligatoire : la table contient déjà des lignes
    op.add_column('cabinets', sa.Column('plan', sa.String(length=32), nullable=False, server_default='cabinet'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cabinets', 'plan')
    # ### end Alembic commands ###
